spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      postgresql: debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG